// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootShop.DataAccess.Data;

namespace bootShop.DataAccess.Migrations
{
    [DbContext(typeof(bootShopDbContext))]
    [Migration("20220503171833_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tablet"
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "16 gb ram",
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://cdn.dsmcdn.com//ty209/product/media/images/20211025/14/155912969/117794442/1/1_org.jpg",
                            Name = "Apple Macbook Air",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "16 gb ram",
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://cdn.dsmcdn.com//ty209/product/media/images/20211025/14/155912969/117794442/1/1_org.jpg",
                            Name = "Apple Macbook Air",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://m.media-amazon.com/images/I/71ZiSXOdnhL._AC_SL1500_.jpg",
                            Name = "Iphone",
                            Price = 15000.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://m.media-amazon.com/images/I/71ZiSXOdnhL._AC_SL1500_.jpg",
                            Name = "Iphone",
                            Price = 15000.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://m.media-amazon.com/images/I/71ZiSXOdnhL._AC_SL1500_.jpg",
                            Name = "Iphone",
                            Price = 15000.0
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.HasOne("bootShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
